= RTC Library for Arduino =

The RTC library enables an ATSAME/D51 board to take control of the internal RTC.

Using CRYSTALLESS defines to automatically switch to the ULP32k osc when no external crystal is avaialble.

Needs some work...

Loading time from backup needs work, not very clean at the moment. Checking reset cause needs to be reworked to include BOD1.2? Need to configure PM, Vbat mux? Currently allows overwriting of the "DO NOT MODIFY" ULP32K calibration register values. Mine is 2x slow without loading 0x23. The default value is hidden in userpage, and mine loads 0x00 on it's own. Maybe use the RTC PPM calibration instead? Crystal untested, I don't have a crystal board just yet.

== License ==

Copyright (c) Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
